//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubuoy.UserAuthentication {
    
    
    public partial class Forms {
        
        /// <summary>
        /// addProject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ubuoy.UserAuthentication.UsersControl.addProject addProject;
        
        /// <summary>
        /// addSkill control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ubuoy.UserAuthentication.UsersControl.addSkill addSkill;
        
        /// <summary>
        /// editUserInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ubuoy.UserAuthentication.UsersControl.EditUserInfo editUserInfo;
        
        /// <summary>
        /// addTask control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ubuoy.UserAuthentication.UsersControl.addTask addTask;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Ubuoy.UserAuthentication.FormsMaster Master {
            get {
                return ((Ubuoy.UserAuthentication.FormsMaster)(base.Master));
            }
        }
    }
}
